version: '3'

services:
  app1:
    build:
      context: .
      args:
        APP_NAME: "app1"
    volumes:
      - logs:/app/logs
  app2:
    build:
      context: .
      args:
        APP_NAME: "app2"
    volumes:
      - logs:/app/logs

volumes:
  logs:

