version: "3.9"

services:
  nginx-proxy:
    image: nginx
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
      - target: 443
        published: 8443
        protocol: tcp
        mode: host        
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/certs/cert.pem
      - ./key.pem:/etc/nginx/certs/key.pem
    networks:
      - mynet

  app:
    image: nginx
    deploy:
      replicas: 3
    networks:
      - mynet
    volumes:
      - ./nginx-app.conf:/etc/nginx/nginx.conf
      - ./index-app.html:/usr/share/nginx/html/index.html


networks:
  mynet:
    driver: overlay
    attachable: true

